import numpy as np
import time
import torch
from scipy.integrate import solve_ivp

from pyresdmd.dicts.chebyshev_dictionary import ChebyshevDictionary
from pyresdmd.dicts import TensorProductDictionary
from pyresdmd.dicts.hermite_dictionary import HermiteDictionary
from pyresdmd.dicts.nn.relu.relu_dictionary import ReLUDictionary
from pyresdmd.dicts.trainable_dictionary import TrainableDictionary
from pyresdmd.compute.spectra import (
    compute_eigendecomposition_from_weights,
    compute_pseudospectra,
)
from pyresdmd.utils.helpers import benchmark_metrics
from pyresdmd.utils.plotters import plot_curve, plot_pseudospec

def duffing_cts(
    initial_states: list[torch.Tensor],
    dt: float = 0.05,
    delta: float = 0.3,
    alpha: float = -1.0,
    beta: float = 1.0,
    steps: int = 200,
    noise: float = 0.0,
    device: str = None,
    method: str = "DOP853",
    rtol: float = 1e-9,
    atol: float = 1e-11,
    max_step: float = np.inf,
) -> tuple[torch.Tensor, torch.Tensor]:
    """
    [GENERATED BY CHATGPT PLUS] 
    Simulates the continuous-time Duffing oscillator using scipy.integrate.solve_ivp.

    The Duffing oscillator is governed by

        dx/dt = v
        dv/dt = -delta*v - alpha*x - beta*x^3

    This function integrates the continuous ODE and samples the solution at times

        t = 0, dt, 2*dt, ..., steps*dt.

    It returns snapshot pairs (x, y), where y[i] is the state reached from x[i]
    after one sampling interval dt.

    Parameters
    ----------
    initial_states : list[torch.Tensor]
        List of initial states. Each state must have shape (2,) or (1, 2),
        representing [x_0, v_0].

    dt : float
        Sampling time interval. Must be positive. Default 0.05.

    delta : float
        Damping coefficient. Default 0.3.

    alpha : float
        Linear stiffness coefficient. Default -1.0.

    beta : float
        Nonlinear stiffness coefficient. Default 1.0.

    steps : int
        Number of sampled time steps for each trajectory. Default 200.

    noise : float
        Standard deviation of optional Gaussian observation noise added to
        sampled states after integration. Default 0.0.

        Note: this is observation noise, not process noise. solve_ivp solves
        deterministic ODEs.

    device : str
        Torch device for returned tensors. If None, uses the device of the
        first initial state.

    method : str
        solve_ivp integration method. Default "DOP853", a high-order explicit
        Runge-Kutta method suitable for accurate non-stiff integration.

        You can also use "RK45" if you want SciPy's default method.

    rtol : float
        Relative tolerance for solve_ivp. Default 1e-9.

    atol : float
        Absolute tolerance for solve_ivp. Default 1e-11.

    max_step : float
        Maximum internal solver step. Default np.inf, allowing solve_ivp to
        choose adaptive internal steps.

        If you want to force the solver not to step farther than the sampling
        interval, set max_step=dt.

    Returns
    -------
    x, y : tuple[torch.Tensor, torch.Tensor]
        Snapshot data with shape

            x.shape == (steps * len(initial_states), 2)
            y.shape == (steps * len(initial_states), 2)

        For each row i, y[i] is the sampled state one dt later than x[i].
    """

    if not initial_states:
        raise ValueError("initial_states must be a non-empty list of torch tensors")

    if dt <= 0:
        raise ValueError("dt must be positive")

    if steps < 0:
        raise ValueError("steps must be non-negative")

    if noise < 0:
        raise ValueError("noise must be non-negative")

    if rtol <= 0:
        raise ValueError("rtol must be positive")

    if atol <= 0:
        raise ValueError("atol must be positive")

    if max_step <= 0:
        raise ValueError("max_step must be positive")

    if device is None:
        out_device = initial_states[0].device
    else:
        out_device = torch.device(device)

    def _sanitize_state(initial_state: torch.Tensor) -> torch.Tensor:
        """
        Checks that initial_state is a torch tensor of shape (2,) or (1, 2),
        and converts it to shape (1, 2).
        """
        if not torch.is_tensor(initial_state):
            raise TypeError("Each initial state must be a torch.Tensor")

        if initial_state.ndim == 1 and initial_state.shape[0] == 2:
            state = initial_state.unsqueeze(0)
        elif initial_state.ndim == 2 and initial_state.shape == (1, 2):
            state = initial_state
        else:
            raise ValueError("Each initial state must have shape (2,) or (1, 2)")

        if not torch.is_floating_point(state):
            raise TypeError("Each initial state must use a floating-point dtype")

        return state.to(device=out_device)

    base_state = _sanitize_state(initial_states[0])
    dtype = base_state.dtype

    # Existing Euler version returns empty x and y if steps == 0.
    if steps == 0:
        empty = torch.empty((0, 2), device=out_device, dtype=dtype)
        return empty, empty

    # Stack all initial states into one array of shape (n_trajectories, 2).
    y0_torch = torch.cat(
        [_sanitize_state(initial).to(dtype=dtype) for initial in initial_states],
        dim=0,
    )

    n_trajectories = y0_torch.shape[0]

    # solve_ivp works with NumPy arrays on CPU.
    # Use float64 for integration accuracy, then cast back to the original dtype.
    y0_np = y0_torch.detach().cpu().to(dtype=torch.float64).numpy()

    # Flatten to shape (2 * n_trajectories,).
    # Ordering is [x_0, v_0, x_1, v_1, ..., x_{N-1}, v_{N-1}].
    y0_flat = y0_np.reshape(-1)

    def rhs(t: float, y_flat: np.ndarray) -> np.ndarray:
        """
        Vectorized Duffing RHS for all trajectories at once.

        y_flat has shape (2 * n_trajectories,).
        We reshape it to (n_trajectories, 2), where columns are [x, v].
        """
        y = y_flat.reshape(n_trajectories, 2)

        x = y[:, 0]
        v = y[:, 1]

        dxdt = v
        dvdt = -delta * v - alpha * x - beta * x**3

        dydt = np.empty_like(y)
        dydt[:, 0] = dxdt
        dydt[:, 1] = dvdt

        return dydt.reshape(-1)

    t0 = 0.0
    tf = steps * dt
    t_eval = np.linspace(t0, tf, steps + 1)

    sol = solve_ivp(
        fun=rhs,
        t_span=(t0, tf),
        y0=y0_flat,
        method=method,
        t_eval=t_eval,
        rtol=rtol,
        atol=atol,
        max_step=max_step,
    )

    if not sol.success:
        raise RuntimeError(f"solve_ivp failed: {sol.message}")

    # sol.y has shape (2 * n_trajectories, steps + 1).
    # Convert to shape (steps + 1, n_trajectories, 2).
    states_np = sol.y.T.reshape(steps + 1, n_trajectories, 2)

    states = torch.as_tensor(states_np, device=out_device, dtype=dtype)

    if noise > 0:
        # Observation noise added after continuous-time integration.
        # This mirrors noisy sampled measurements rather than stochastic dynamics.
        states = states + noise * torch.randn_like(states)

    # Convert from shape (steps + 1, n_trajectories, 2)
    # to shape (n_trajectories, steps + 1, 2), so the final ordering matches
    # your original implementation:
    #
    # trajectory 0 all times, then trajectory 1 all times, etc.
    states_by_traj = states.permute(1, 0, 2).contiguous()

    x = states_by_traj[:, :-1, :].reshape(-1, 2)
    y = states_by_traj[:, 1:, :].reshape(-1, 2)

    return x, y

def duffing(initial_states : list[torch.Tensor],
    dt : float = 0.05,
    delta : float = 0.3,
    alpha : float = -1.0,
    beta : float = 1.0,
    steps : int = 200,
    noise : float = 0.0,
    device : str = None         
    ) -> tuple[torch.Tensor, torch.Tensor]:
    '''
        Simulates the Duffing oscillator. The Duffing oscillator is governed by the coupled ODEs:
            dv/dt = -delta*v - alpha*x - beta*x^3
            dx/dt = v
        We discretize this using Euler:
            x_(n + 1) = x_n + (Delta t) * v_n + eps_n
            v_(n + 1) = v_n + (Delta t) * (-delta*v_n - alpha*x_n - beta*x_n^3) + eps_n'
        where eps_n, eps_n' are optional random noise, implemented as Normal(0, noise^2).

        Parameters
        ------------------------------
        initial_states : list[torch.Tensor]
            List of initial states to evolve, typically produced by random sampling.

        dt : float
            Time-step to use for discretization. Must be positive. Default 0.05.

        delta : float
            The damping coefficient. Default 0.3.

        alpha : float
            The linear stiffness coefficient. Default -1.0.

        beta : float
            The nonlinear stiffness coefficient. Default 1.0.

        steps : int
            Number of steps to run each simulation for. Default 200.

        noise : float
            Noise level. Default 0.0.

        Returns
        ------------------------------
        x, y
            Output trajectory data as tensors of pairs (x_i, v_i). y[i] is the state that x[i] evolves to after one time step.

            Has shape (total_trajectory_length, 2), where total_trajectory_length = steps * len(initial_states).
    '''
    if not initial_states:
        raise ValueError("initial_states must be a non-empty list of torch tensors")

    if dt <= 0:
        raise ValueError("dt must be positive")

    if steps < 0:
        raise ValueError("steps must be non-negative")

    if noise < 0:
        raise ValueError("noise must be non-negative")

    if device is None:
        device = initial_states[0].device

    def _sanitize_state(initial_state : torch.Tensor) -> torch.Tensor:
        '''Checks that the initial state is a torch tensor of shape (2,) or (1, 2) and converts it to shape (1, 2) if necessary.'''
        if not torch.is_tensor(initial_state):
            raise TypeError("Each initial state must be a torch.Tensor")

        # valid starting points can be shape (2,), meaning [x_0, v_0], or shape (1, 2), meaning [[x_0, v_0]]
        # we convert the former to the latter so all trajectories have consistent shape (steps + 1, 2)
        if initial_state.ndim == 1 and initial_state.shape[0] == 2:
            state = initial_state.unsqueeze(0)
        elif initial_state.ndim == 2 and initial_state.shape == (1, 2):
            state = initial_state
        else:
            raise ValueError("Each initial state must have shape (2,) or (1, 2)")

        return state.to(device = device)

    base_state = _sanitize_state(initial_states[0])
    dtype = base_state.dtype
    device = base_state.device

    states = []

    for initial in initial_states:
        trajectory = [_sanitize_state(initial).to(dtype = dtype)]
        
        for _ in range(steps):
            state = trajectory[-1]
            x_0, v_0 = state[:, 0], state[:, 1]
            x_noise = noise * torch.randn_like(x_0)
            v_noise = noise * torch.randn_like(v_0)
            x_1 = x_0 + dt * v_0 + x_noise
            v_1 = v_0 + dt * (-delta * v_0 - alpha * x_0 - beta * x_0**3) + v_noise
            trajectory.append(torch.stack((x_1, v_1), dim = 1))
        states.append(torch.cat(trajectory, dim = 0))
    
    x = torch.cat([state[:-1] for state in states], dim = 0).to(device = device, dtype = dtype)
    y = torch.cat([state[1:] for state in states], dim = 0).to(device = device, dtype = dtype)

    return x, y


def duffing_demo(noise : float = 0.0,
    n_trajectories : int = 1500,
    steps : int = 40,
    epochs : int = 1000,
    patience : int = 50,
    dictionary_size : int = 100,
    repeats : int = 15,
    save_plots : bool = True,
    save_report : bool = True,
    device : str = None
) -> str:
    '''
    Replicates the Duffing oscillator simulation used in our paper.

    The function runs repeated independent trajectory simulations, trains a ReLU dictionary,
    and compares it against an untrained Chebyshev tensor-product dictionary.

    The function does the following:
    1. records the resultant loss, condition number and forecast error.
    2. computes these quantities for a Chebyshev dictionary.
    3. computes a pseudospectral plot for the untrained ReLU dictionary, the trained ReLU dictionary, and the Chebyshev dictionary.

    If save_report = True, a .log file is saved reporting the mean and standard deviation of the loss,
    condition number and forecast error.

    Parameters
    ------------------------------
    noise : float
        Noise level of simulation.

    n_trajectories : int
        Number of initial states to evolve. Default 1500.

    steps : int
        Number of steps to evolve each initial state. Default 40.

    epochs : int
        Number of training epochs for the ReLU dictionary.

    patience : int
        Number of non-improvement epochs allowed before early stopping.

    dictionary_size : int
        Number of dictionary functions to consider for both the ReLU dictionary and the Chebyshev dictionary.

        The Chebyshev dictionary will be the tensor product of two Chebyshev dictionaries of size sqrt(dictionary_size).

        Default 100.

    repeats : int
        Number of times to repeat the simulation. Default 15.

    save_plots : bool
        Whether to save plots locally. Default True.

    save_report : bool
        Whether to save report locally. Default True.

    device : str
        Device to run simulation on. Defaults to CPU if not provided.
    '''
    t = time.time()
    if not device:
        device = 'cpu'

    l_test_losses = []
    l_test_cond_nums = []
    l_test_forecast_errors = []

    l_chebyshev_losses = []
    l_chebyshev_cond_nums = []
    l_chebyshev_forecast_errors = []
    saved_files = []

    def rand_point() -> torch.Tensor:
        '''Generates a random point in the state space. Samples uniformly from the box [-3, 3]^2'''
        return 6*torch.rand(2, device = device) - 3 # sample uniformly from [-3, 3]^2
    
    for i in range(repeats):
        initial_states = [rand_point() for _ in range(n_trajectories)]
        base = ReLUDictionary(input_dim = 2, n_functions = dictionary_size)
        dictionary = TrainableDictionary(base)
        dictionary.to(device)
        x, y = duffing(initial_states, dt = 0.05, delta = 0.0, alpha = -1.0, beta = 1.0, steps = steps, noise = noise, device = device)

        report = dictionary.report(x, y)
        init_eigvals = report['eigenvalues']
        Psi_X, Psi_Y = dictionary.evaluate(x), dictionary.evaluate(y)
        init_pseudospec = compute_pseudospectra(Psi_X, Psi_Y)

        trained = dictionary.fit(x, y, epochs = epochs, patience = patience)
        train_losses = trained['train_losses']
        test_losses = trained['test_losses']
        train_cond_nums = trained['train_cond_nums']
        test_cond_nums = trained['test_cond_nums']
        train_forecast_errors = trained['train_forecast_errors']
        test_forecast_errors = trained['test_forecast_errors']
        final_epoch = trained['final_epoch']

        best_report = dictionary.report(x, y)
        best_loss = best_report['loss']
        best_cond_num = best_report['cond_num']
        best_forecast_error = best_report['forecast_error']
        Psi_X, Psi_Y = dictionary.evaluate(x), dictionary.evaluate(y)
        final_pseudospec = compute_pseudospectra(Psi_X, Psi_Y)
        W = torch.ones(x.shape[0], device = x.device) / x.shape[0]
        final_eigvals, _ = compute_eigendecomposition_from_weights(Psi_X, Psi_Y, W)

        size = int(dictionary_size**0.5)
        chebyshev_dict = TensorProductDictionary(HermiteDictionary(size), HermiteDictionary(size))
        chebyshev_dict.to(device)
        chebyshev_metrics = benchmark_metrics(chebyshev_dict, x, y)
        chebyshev_pseudospec = chebyshev_metrics['pseudospec']
        Lambda = chebyshev_metrics['Lambda']
        chebyshev_cond_num = chebyshev_metrics['cond_num']
        chebyshev_loss = chebyshev_metrics['loss']
        chebyshev_forecast_error = chebyshev_metrics['forecast_error']

        if i == 0 and save_plots:
            f1 = f'duffing_sim_loss_{int(time.time())}.png'
            saved_files.append(f1)
            plot_curve(final_epoch, train_losses, test_losses, add_values = {'Chebyshev': chebyshev_loss},
                       displayname = 'Duffing Oscillator', ylabel = 'Loss', save_plot = True,
                       filename = f1)

            f2 = f'duffing_sim_cond_num_{int(time.time())}.png'
            saved_files.append(f2)
            plot_curve(final_epoch, train_cond_nums, test_cond_nums, add_values = {'Chebyshev': chebyshev_cond_num},
                       displayname = 'Duffing Oscillator', ylabel = 'Condition number', save_plot = True,
                       filename = f2)

            f3 = f'duffing_sim_forecast_{int(time.time())}.png'
            saved_files.append(f3)
            plot_curve(final_epoch, train_forecast_errors, test_forecast_errors, add_values = {'Chebyshev': chebyshev_forecast_error},
                       displayname = 'Duffing Oscillator', ylabel = 'Forecast error', save_plot = True,
                       filename = f3)

        if i == 0 and save_plots:
            eps_levels = [1e-3, 2e-3, 5e-3, 1e-2, 2e-2, 5e-2, 1e-1, 2e-1, 5e-1]
            re_vals = init_pseudospec['re_vals']
            im_vals = init_pseudospec['im_vals']
            tau_grid = init_pseudospec['tau_grid']
            f4 = f'duffing_pseudospec_init_relu_{int(time.time())}.png'
            saved_files.append(f4)
            plot_pseudospec(re_vals, im_vals, tau_grid, eps_levels, eigvals = init_eigvals, unit_circle = True, save = True, displayname = 'Psuedospectrum of Duffing Oscillator (Untrained ReLU)', filename = f4)
            re_vals = final_pseudospec['re_vals']
            im_vals = final_pseudospec['im_vals']
            tau_grid = final_pseudospec['tau_grid']
            f5 = f'duffing_pseudospec_final_relu_{int(time.time())}.png'
            saved_files.append(f5)
            plot_pseudospec(re_vals, im_vals, tau_grid, eps_levels, eigvals = final_eigvals, unit_circle = True, save = True, displayname = 'Psuedospectrum of Duffing Oscillator (Trained ReLU)', filename = f5)
            re_vals = chebyshev_pseudospec['re_vals']
            im_vals = chebyshev_pseudospec['im_vals']
            tau_grid = chebyshev_pseudospec['tau_grid']
            f6 = f'duffing_pseudospec_chebyshev_{int(time.time())}.png'
            saved_files.append(f6)
            plot_pseudospec(re_vals, im_vals, tau_grid, eps_levels, eigvals = Lambda, unit_circle = True, save = True, displayname = 'Psuedospectrum of Duffing Oscillator (Chebyshev)', filename = f6)

        l_test_cond_nums.append(best_cond_num)
        l_test_forecast_errors.append(best_forecast_error)
        l_test_losses.append(best_loss)
        l_chebyshev_losses.append(chebyshev_loss)
        l_chebyshev_cond_nums.append(chebyshev_cond_num)
        l_chebyshev_forecast_errors.append(chebyshev_forecast_error)

    l_test_cond_nums = np.array(l_test_cond_nums)
    l_test_forecast_errors = np.array(l_test_forecast_errors)
    l_test_losses = np.array(l_test_losses)
    l_chebyshev_losses = np.array(l_chebyshev_losses)
    l_chebyshev_cond_nums = np.array(l_chebyshev_cond_nums)
    l_chebyshev_forecast_errors = np.array(l_chebyshev_forecast_errors)

    t1 = time.time()
    duration = int(t1 - t)
    report = f"""
        Ran Duffing Oscillator simulation {repeats} times. Took {duration} seconds.
        ----------------------------------------------------------------------------
            Mean best loss for ReLU: {l_test_losses.mean()} (std: {l_test_losses.std()})
            Mean condition number for best ReLU: {l_test_cond_nums.mean()} (std: {l_test_cond_nums.std()})
            Mean forecast error for best ReLU: {l_test_forecast_errors.mean()} (std: {l_test_forecast_errors.std()})
            ---------------------------------------------------------------------------------
            Mean loss for Hermite: {l_chebyshev_losses.mean()} (std: {l_chebyshev_losses.std()})
            Mean condition number for Hermite: {l_chebyshev_cond_nums.mean()} (std: {l_chebyshev_cond_nums.std()})
            Mean forecast number for Hermite: {l_chebyshev_forecast_errors.mean()} (std: {l_chebyshev_forecast_errors.std()})
            """

    if save_plots:
        if saved_files:
            report += """
            ---------------------------------------------------------------------------------
            Saved files:
            """
            report += "\n" + "\n".join(f"                {filename}" for filename in saved_files)

    if save_report:
        with open(f"log_{int(time.time())}.log", "x") as file:
            file.write(report)
    
    return report

if __name__ == '__main__':
    duffing_demo(noise = 0.0, n_trajectories = 1500, steps = 40, epochs = 500, patience = 50, dictionary_size = 100, repeats = 15, save_plots = False, save_report = True, device = 'cuda:0')