import numpy as np
import time
import torch
from scipy.integrate import solve_ivp

from pyresdmd.compute.spectra import (
	compute_eigendecomposition_from_weights,
	compute_pseudospectra,
)
from pyresdmd.dicts.fourier_mode_dictionary import FourierModeDictionary
from pyresdmd.dicts.hermite_dictionary import HermiteDictionary
from pyresdmd.dicts import TensorProductDictionary
from pyresdmd.dicts.nn.relu.relu_dictionary import ReLUDictionary
from pyresdmd.dicts.trainable_dictionary import TrainableDictionary
from pyresdmd.utils.helpers import benchmark_metrics
from pyresdmd.utils.plotters import plot_curve, plot_pseudospec

def pendulum_cts(
    initial_states: list[torch.Tensor],
    dt: float = 0.1,
    g: float = 9.81,
    steps: int = 120,
    noise: float = 0.0,
    device: str = None,
    method: str = "DOP853",
    rtol: float = 1e-9,
    atol: float = 1e-11,
    max_step: float = np.inf,
) -> tuple[torch.Tensor, torch.Tensor]:
    """
	[GENERATED BY OPUS]
    Simulates the continuous-time simple pendulum using scipy.integrate.solve_ivp.

    The pendulum is governed by

        dtheta/dt = omega
        domega/dt = -g * sin(theta)

    This function integrates the continuous ODE and samples the solution at times

        t = 0, dt, 2*dt, ..., steps*dt.

    It returns snapshot pairs (x, y), where y[i] is the state reached from x[i]
    after one sampling interval dt.

    Parameters
    ----------
    initial_states : list[torch.Tensor]
        List of initial states. Each state must have shape (2,) or (1, 2),
        representing [theta_0, omega_0].

    dt : float
        Sampling time interval. Must be positive. Default 0.1.

    g : float
        Gravitational acceleration (coefficient on sin(theta)). Default 9.81.

    steps : int
        Number of sampled time steps for each trajectory. Default 120.

    noise : float
        Standard deviation of optional Gaussian observation noise added to
        sampled states after integration. Default 0.0.

        Note: this is observation noise, not process noise. solve_ivp solves
        deterministic ODEs.

    device : str
        Torch device for returned tensors. If None, uses the device of the
        first initial state.

    method : str
        solve_ivp integration method. Default "DOP853", a high-order explicit
        Runge-Kutta method suitable for accurate non-stiff integration.

        You can also use "RK45" if you want SciPy's default method.

    rtol : float
        Relative tolerance for solve_ivp. Default 1e-9.

    atol : float
        Absolute tolerance for solve_ivp. Default 1e-11.

    max_step : float
        Maximum internal solver step. Default np.inf, allowing solve_ivp to
        choose adaptive internal steps.

        If you want to force the solver not to step farther than the sampling
        interval, set max_step=dt.

    Returns
    -------
    x, y : tuple[torch.Tensor, torch.Tensor]
        Snapshot data with shape

            x.shape == (steps * len(initial_states), 2)
            y.shape == (steps * len(initial_states), 2)

        For each row i, y[i] is the sampled state one dt later than x[i].
    """

    if not initial_states:
        raise ValueError("initial_states must be a non-empty list of torch tensors")

    if dt <= 0:
        raise ValueError("dt must be positive")

    if steps < 0:
        raise ValueError("steps must be non-negative")

    if noise < 0:
        raise ValueError("noise must be non-negative")

    if rtol <= 0:
        raise ValueError("rtol must be positive")

    if atol <= 0:
        raise ValueError("atol must be positive")

    if max_step <= 0:
        raise ValueError("max_step must be positive")

    if device is None:
        out_device = initial_states[0].device
    else:
        out_device = torch.device(device)

    def _sanitize_state(initial_state: torch.Tensor) -> torch.Tensor:
        """
        Checks that initial_state is a torch tensor of shape (2,) or (1, 2),
        and converts it to shape (1, 2).
        """
        if not torch.is_tensor(initial_state):
            raise TypeError("Each initial state must be a torch.Tensor")

        if initial_state.ndim == 1 and initial_state.shape[0] == 2:
            state = initial_state.unsqueeze(0)
        elif initial_state.ndim == 2 and initial_state.shape == (1, 2):
            state = initial_state
        else:
            raise ValueError("Each initial state must have shape (2,) or (1, 2)")

        if not torch.is_floating_point(state):
            raise TypeError("Each initial state must use a floating-point dtype")

        return state.to(device=out_device)

    base_state = _sanitize_state(initial_states[0])
    dtype = base_state.dtype

    # Existing Euler version returns empty x and y if steps == 0.
    if steps == 0:
        empty = torch.empty((0, 2), device=out_device, dtype=dtype)
        return empty, empty

    # Stack all initial states into one array of shape (n_trajectories, 2).
    y0_torch = torch.cat(
        [_sanitize_state(initial).to(dtype=dtype) for initial in initial_states],
        dim=0,
    )

    n_trajectories = y0_torch.shape[0]

    # solve_ivp works with NumPy arrays on CPU.
    # Use float64 for integration accuracy, then cast back to the original dtype.
    y0_np = y0_torch.detach().cpu().to(dtype=torch.float64).numpy()

    # Flatten to shape (2 * n_trajectories,).
    # Ordering is [theta_0, omega_0, theta_1, omega_1, ...].
    y0_flat = y0_np.reshape(-1)

    def rhs(t: float, y_flat: np.ndarray) -> np.ndarray:
        """
        Vectorized pendulum RHS for all trajectories at once.

        y_flat has shape (2 * n_trajectories,).
        We reshape it to (n_trajectories, 2), where columns are [theta, omega].
        """
        y = y_flat.reshape(n_trajectories, 2)

        theta = y[:, 0]
        omega = y[:, 1]

        dthetadt = omega
        domegadt = -g * np.sin(theta)

        dydt = np.empty_like(y)
        dydt[:, 0] = dthetadt
        dydt[:, 1] = domegadt

        return dydt.reshape(-1)

    t0 = 0.0
    tf = steps * dt
    t_eval = np.linspace(t0, tf, steps + 1)

    sol = solve_ivp(
        fun=rhs,
        t_span=(t0, tf),
        y0=y0_flat,
        method=method,
        t_eval=t_eval,
        rtol=rtol,
        atol=atol,
        max_step=max_step,
    )

    if not sol.success:
        raise RuntimeError(f"solve_ivp failed: {sol.message}")

    # sol.y has shape (2 * n_trajectories, steps + 1).
    # Convert to shape (steps + 1, n_trajectories, 2).
    states_np = sol.y.T.reshape(steps + 1, n_trajectories, 2)

    states = torch.as_tensor(states_np, device=out_device, dtype=dtype)

    if noise > 0:
        # Observation noise added after continuous-time integration.
        states = states + noise * torch.randn_like(states)

    # Convert to shape (n_trajectories, steps + 1, 2):
    # trajectory 0 all times, then trajectory 1 all times, etc.
    states_by_traj = states.permute(1, 0, 2).contiguous()

    x = states_by_traj[:, :-1, :].reshape(-1, 2)
    y = states_by_traj[:, 1:, :].reshape(-1, 2)

    return x, y

def sim(initial_states : list[torch.Tensor],
	dt : float = 0.1,
	g : float = 9.81,
	steps : int = 120,
	noise : float= 0.0,
	device : str = None) -> tuple[torch.Tensor, torch.Tensor]:
	'''
		Simulates a simple pendulum (angle, angular velocity) using explicit Euler.

		Discretization used:
			theta_{n+1} = theta_n + dt * omega_n + eps_theta
			omega_{n+1} = omega_n - dt * g * sin(theta_{n+1}) + eps_omega

		Parameters
		------------------------------
		initial_states : list[torch.Tensor]
			List of initial states to evolve, as tensors of shape (2,) or (1,2).

		dt : float
			Time-step to use for discretization. Must be positive

		g : float
			Gravitational acceleration. Default 9.81.

		steps : int
			Number of steps to run each simulation for. Default 120.

		noise : float
			Noise level. Default 0.0.

		device : str
			Device to send trajectory data to.

		Returns
		------------------------------
		x, y
			Output trajectory data as tensors of pairs (theta, omega). y[i] is the state that x[i] evolves to after one time step.
	'''
	if not initial_states:
		raise ValueError("initial_states must be a non-empty list of torch tensors")
	if dt <= 0:
		raise ValueError("dt must be positive")
	if steps < 0:
		raise ValueError("steps must be non-negative")
	if noise < 0:
		raise ValueError("noise must be non-negative")

	if device is None:
		device = initial_states[0].device

	def _sanitize_state(initial_state : torch.Tensor) -> torch.Tensor:
		'''Checks that the initial state is a torch tensor of shape (2,) or (1, 2) and converts it to shape (1, 2) if necessary.'''
		if not torch.is_tensor(initial_state):
			raise TypeError("Each initial state must be a torch.Tensor")

		if initial_state.ndim == 1 and initial_state.shape[0] == 2:
			state = initial_state.unsqueeze(0)
		elif initial_state.ndim == 2 and initial_state.shape == (1, 2):
			state = initial_state
		else:
			raise ValueError("Each initial state must have shape (2,) or (1, 2)")

		return state.to(device = device)

	base_state = _sanitize_state(initial_states[0])
	dtype = base_state.dtype
	device = base_state.device

	states = []

	for initial in initial_states:
		trajectory = [_sanitize_state(initial).to(dtype = dtype)]

		for _ in range(steps):
			state = trajectory[-1]
			theta_0, omega_0 = state[:, 0], state[:, 1]
			theta_noise = noise * torch.randn_like(theta_0)
			omega_noise = noise * torch.randn_like(omega_0)
			theta_1 = theta_0 + dt * omega_0 + theta_noise
			omega_1 = omega_0 - dt * g * torch.sin(theta_1) + omega_noise
			trajectory.append(torch.stack((theta_1, omega_1), dim = 1))
		states.append(torch.cat(trajectory, dim = 0))

	x = torch.cat([state[:-1] for state in states], dim = 0).to(device = device, dtype = dtype)
	y = torch.cat([state[1:] for state in states], dim = 0).to(device = device, dtype = dtype)

	return x, y


def pendulum_demo(noise : float = 0.0,
	n_trajectories : int = 140,
	steps : int = 126,
	epochs : int = 1000,
	patience : int = 50,
	dictionary_size : int = 60,
	repeats : int = 15,
	save_plots : bool = True,
	save_report : bool = True,
	device : str = None
) -> str:
	'''
	Replicates the Pendulum simulation used in our paper.

	The function runs repeated independent trajectory simulations, trains a ReLU dictionary,
	and compares it against an untrained Fourier x Hermite tensor-product dictionary.

	The function does the following:
	1. records the resultant loss, condition number and forecast error.
	2. computes these quantities for a Fourier x Hermite dictionary.
	3. computes a pseudospectral plot for the untrained ReLU dictionary, the trained ReLU dictionary, and the Fourier x Hermite dictionary.

	If save_report = True, a .log file is saved reporting the mean and standard deviation of the loss,
	condition number and forecast error.

	Parameters
	------------------------------
	noise : float
		Noise level of simulation.

	n_trajectories : int
		Number of initial states to evolve. Default 140.

	steps : int
		Number of steps to evolve each initial state. Default 126.

	epochs : int
		Number of training epochs for the ReLU dictionary.

	patience : int
		Number of non-improvement epochs allowed before early stopping.

	dictionary_size : int
		Number of dictionary functions to consider for both the ReLU dictionary and the tensor-product dictionary.

		The Fourier x Hermite dictionary will be the tensor product of a FourierModeDictionary and a HermiteDictionary,
		with sizes chosen from sqrt(dictionary_size) split in a 5:3 ratio (Fourier:Hermite).

		Default 60.

	repeats : int
		Number of times to repeat the simulation. Default 15.

	save_plots : bool
		Whether to save plots locally. Default True.

	save_report : bool
		Whether to save report locally. Default True.

	device : str
		Device to run simulation on. Defaults to CPU if not provided.
	'''

	t = time.time()
	if not device:
		device = 'cpu'

	l_test_losses = []
	l_test_cond_nums = []
	l_test_forecast_errors = []

	l_fh_losses = []
	l_fh_cond_nums = []
	l_fh_forecast_errors = []
	saved_files = []

	def rand_point() -> torch.Tensor:
		'''Generates a random point in the state space. We pick a radius uniformly from [0.3, 2.3] and an angle uniformly from [0, 2pi], and return the corresponding point in Cartesian coordinates.'''
		r = 2*torch.rand(1) + 0.3
		theta = 2*torch.pi*torch.rand(1)
		return torch.stack((r * torch.cos(theta), r * torch.sin(theta))).squeeze()

	for i in range(repeats):
		initial_states = [rand_point() for _ in range(n_trajectories)]
		base = ReLUDictionary(input_dim = 2, n_functions = dictionary_size)
		dictionary = TrainableDictionary(base)
		dictionary.to(device)
		x, y = sim(initial_states, dt = 0.05, g = 9.81, steps = steps, noise = noise, device = device)

		report = dictionary.report(x, y)
		init_eigvals = report['eigenvalues']
		Psi_X, Psi_Y = dictionary.evaluate(x), dictionary.evaluate(y)
		init_pseudospec = compute_pseudospectra(Psi_X, Psi_Y)

		trained = dictionary.fit(x, y, epochs = epochs, patience = patience)
		train_losses = trained['train_losses']
		test_losses = trained['test_losses']
		train_cond_nums = trained['train_cond_nums']
		test_cond_nums = trained['test_cond_nums']
		train_forecast_errors = trained['train_forecast_errors']
		test_forecast_errors = trained['test_forecast_errors']
		final_epoch = trained['final_epoch']

		best_report = dictionary.report(x, y)
		best_loss = best_report['loss']
		best_cond_num = best_report['cond_num']
		best_forecast_error = best_report['forecast_error']
		Psi_X, Psi_Y = dictionary.evaluate(x), dictionary.evaluate(y)
		final_pseudospec = compute_pseudospectra(Psi_X, Psi_Y)
		W = torch.ones(x.shape[0], device = x.device) / x.shape[0]
		final_eigvals, _ = compute_eigendecomposition_from_weights(Psi_X, Psi_Y, W)

		base = int(dictionary_size**0.5)
		total_ratio = 5 + 3
		f_size = max(1, int(round(base * 5/total_ratio)))
		h_size = max(1, int(round(base * 3/total_ratio)))
		if f_size * h_size == 0:
			f_size = max(1, base)
			h_size = max(1, base)
		fh_dict = TensorProductDictionary(FourierModeDictionary(f_size), HermiteDictionary(h_size))
		fh_dict.to(device)
		fh_metrics = benchmark_metrics(fh_dict, x, y)
		Lambda = fh_metrics['Lambda']
		fh_cond_num = fh_metrics['cond_num']
		fh_loss = fh_metrics['loss']
		fh_forecast_error = fh_metrics['forecast_error']

		if i == 0 and save_plots:
			f1 = f'pendulum_sim_loss_{int(time.time())}.png'
			saved_files.append(f1)
			plot_curve(final_epoch, train_losses, test_losses, add_values = {'Fourier x Hermite': fh_loss},
					   displayname = 'Pendulum', ylabel = 'Loss', save_plot = True,
					   filename = f1)

			f2 = f'pendulum_sim_cond_num_{int(time.time())}.png'
			saved_files.append(f2)
			plot_curve(final_epoch, train_cond_nums, test_cond_nums, add_values = {'Fourier x Hermite': fh_cond_num},
						displayname = 'Pendulum', ylabel = 'Condition number', save_plot = True,
						filename = f2)

			f3 = f'pendulum_sim_forecast_{int(time.time())}.png'
			saved_files.append(f3)
			plot_curve(final_epoch, train_forecast_errors, test_forecast_errors, add_values = {'Fourier x Hermite': fh_forecast_error},
						displayname = 'Pendulum', ylabel = 'Forecast error', save_plot = True,
						filename = f3)

		if i == 0 and save_plots:
			eps_levels = [1e-3, 2e-3, 5e-3, 1e-2, 2e-2, 5e-2, 1e-1, 2e-1, 5e-1]
			re_vals = init_pseudospec['re_vals']
			im_vals = init_pseudospec['im_vals']
			tau_grid = init_pseudospec['tau_grid']
			f4 = f'pendulum_pseudospec_init_relu_{int(time.time())}.png'
			saved_files.append(f4)
			plot_pseudospec(re_vals, im_vals, tau_grid, eps_levels, eigvals = init_eigvals, unit_circle = True, save = True, displayname = 'Psuedospectrum of Pendulum (Untrained ReLU)', filename = f4)
			re_vals = final_pseudospec['re_vals']
			im_vals = final_pseudospec['im_vals']
			tau_grid = final_pseudospec['tau_grid']
			f5 = f'pendulum_pseudospec_final_relu_{int(time.time())}.png'
			saved_files.append(f5)
			plot_pseudospec(re_vals, im_vals, tau_grid, eps_levels, eigvals = final_eigvals, unit_circle = True, save = True, displayname = 'Psuedospectrum of Pendulum (Trained ReLU)', filename = f5)
			re_vals = fh_metrics['pseudospec']['re_vals']
			im_vals = fh_metrics['pseudospec']['im_vals']
			tau_grid = fh_metrics['pseudospec']['tau_grid']
			f6 = f'pendulum_pseudospec_fourier_hermite_{int(time.time())}.png'
			saved_files.append(f6)
			plot_pseudospec(re_vals, im_vals, tau_grid, eps_levels, eigvals = Lambda, unit_circle = True, save = True, displayname = 'Psuedospectrum of Pendulum (Fourier x Hermite)', filename = f6)

		l_test_cond_nums.append(best_cond_num)
		l_test_forecast_errors.append(best_forecast_error)
		l_test_losses.append(best_loss)
		l_fh_losses.append(fh_loss)
		l_fh_cond_nums.append(fh_cond_num)
		l_fh_forecast_errors.append(fh_forecast_error)

	l_test_cond_nums = np.array(l_test_cond_nums)
	l_test_forecast_errors = np.array(l_test_forecast_errors)
	l_test_losses = np.array(l_test_losses)
	l_fh_losses = np.array(l_fh_losses)
	l_fh_cond_nums = np.array(l_fh_cond_nums)
	l_fh_forecast_errors = np.array(l_fh_forecast_errors)

	t1 = time.time()
	duration = int(t1 - t)
	report = f"""
		Ran Pendulum simulation {repeats} times. Took {duration} seconds.
		----------------------------------------------------------------------------
			Mean best loss for ReLU: {l_test_losses.mean()} (std: {l_test_losses.std()})
			Mean condition number for best ReLU: {l_test_cond_nums.mean()} (std: {l_test_cond_nums.std()})
			Mean forecast error for best ReLU: {l_test_forecast_errors.mean()} (std: {l_test_forecast_errors.std()})
			---------------------------------------------------------------------------------
			Mean loss for Fourier x Hermite: {l_fh_losses.mean()} (std: {l_fh_losses.std()})
			Mean condition number for Fourier x Hermite: {l_fh_cond_nums.mean()} (std: {l_fh_cond_nums.std()})
			Mean forecast number for Fourier x Hermite: {l_fh_forecast_errors.mean()} (std: {l_fh_forecast_errors.std()})
			"""

	if save_plots:
		if saved_files:
			report += """
			---------------------------------------------------------------------------------
			Saved files:
			"""
			report += "\n" + "\n".join(f"                {filename}" for filename in saved_files)

	if save_report:
		with open(f"log_{int(time.time())}.log", "x") as file:
			file.write(report)
	
	return report